select jsonb_build_object(
'institutes',(select jsonb_build_object('count',count(*),'md5',md5(coalesce(string_agg(coalesce(id::text,'')||'|'||coalesce(code::text,'')||'|'||coalesce(name::text,'')||'|'||coalesce(short_name::text,'')||'|'||coalesce(district::text,'')||'|'||coalesce(locality::text,'')||'|'||(location->>'lat')||'|'||(location->>'lng')||'|'||coalesce(shift_windows::text,''),E'\n' order by id collate "C"),''))) from public.institutes where id in ('inst-27410','inst-27613')),
'subjects',(select jsonb_build_object('count',count(*),'md5',md5(coalesce(string_agg(coalesce(id::text,'')||'|'||coalesce(name::text,''),E'\n' order by id collate "C"),''))) from public.subjects),
'trades',(select jsonb_build_object('count',count(*),'md5',md5(coalesce(string_agg(coalesce(id::text,'')||'|'||coalesce(institute_id::text,'')||'|'||coalesce(name::text,'')||'|'||coalesce(duration_years::text,''),E'\n' order by id collate "C"),''))) from public.trades where institute_id in ('inst-27410','inst-27613')),
'batches',(select jsonb_build_object('count',count(*),'md5',md5(coalesce(string_agg(coalesce(id::text,'')||'|'||coalesce(institute_id::text,'')||'|'||coalesce(trade_id::text,'')||'|'||coalesce(shift::text,'')||'|'||coalesce(unit::text,'')||'|'||coalesce(year::text,''),E'\n' order by id collate "C"),''))) from public.batches where institute_id in ('inst-27410','inst-27613')),
'students',(select jsonb_build_object('count',count(*),'md5',md5(coalesce(string_agg(coalesce(id::text,'')||'|'||coalesce(institute_id::text,'')||'|'||coalesce(batch_id::text,'')||'|'||coalesce(roll_no::text,'')||'|'||coalesce(name::text,'')||'|'||coalesce(father_name::text,''),E'\n' order by id collate "C"),''))) from public.students where institute_id in ('inst-27410','inst-27613')),
'staff',(select jsonb_build_object('count',count(*),'md5',md5(coalesce(string_agg(coalesce(id::text,'')||'|'||coalesce(institute_id::text,'')||'|'||coalesce(trainer_id::text,'')||'|'||coalesce(name::text,'')||'|'||coalesce(role::text,'')||'|'||coalesce(employment_type::text,'')||'|'||coalesce(designation::text,'')||'|'||coalesce(primary_trade_id::text,'')||'|'||array_to_string(secondary_trade_ids,',')||'|'||array_to_string(batch_ids,',')||'|'||coalesce(subject_id::text,'')||'|'||coalesce(multi_trade_allowed::text,''),E'\n' order by id collate "C"),''))) from public.staff where institute_id in ('inst-27410','inst-27613')),
'timetable',(select jsonb_build_object('count',count(*),'md5',md5(coalesce(string_agg(coalesce(id::text,'')||'|'||coalesce(institute_id::text,'')||'|'||coalesce(batch_id::text,'')||'|'||coalesce(instructor_id::text,'')||'|'||coalesce(weekday::text,'')||'|'||coalesce(period_no::text,'')||'|'||coalesce(kind::text,'')||'|'||coalesce(window_start::text,'')||'|'||coalesce(window_end::text,'')||'|'||coalesce(subject_id::text,''),E'\n' order by id collate "C"),''))) from public.timetable where institute_id in ('inst-27410','inst-27613'))
) as fingerprints;
