-- Generated by scripts/supabase/generate-seed.ts (the live smoke-test institute, code 99999). Do not edit by hand.
insert into public.institutes (id,code,name,short_name,district,locality,location,shift_windows) values
('inst-99999','99999','Test Industrial Training Institute (live smoke test)','Test ITI','Test District','Test','{"lat":18.52,"lng":73.8567}'::jsonb,null)
on conflict (id) do update set code=excluded.code,name=excluded.name,short_name=excluded.short_name,district=excluded.district,locality=excluded.locality,location=excluded.location,shift_windows=excluded.shift_windows;
insert into public.trades (id,institute_id,name,duration_years) values
('tst','inst-99999','Test Trade',1)
on conflict (id) do update set institute_id=excluded.institute_id,name=excluded.name,duration_years=excluded.duration_years;
insert into public.batches (id,institute_id,trade_id,shift,unit,year) values
('tst-s1u1','inst-99999','tst',1,1,1)
on conflict (id) do update set institute_id=excluded.institute_id,trade_id=excluded.trade_id,shift=excluded.shift,unit=excluded.unit,year=excluded.year;
insert into public.students (id,institute_id,batch_id,roll_no,name,father_name) values
('tst-s1u1-r01','inst-99999','tst-s1u1',1,'Test Student One','Test Father One'),
('tst-s1u1-r02','inst-99999','tst-s1u1',2,'Test Student Two','Test Father Two'),
('tst-s1u1-r03','inst-99999','tst-s1u1',3,'Test Student Three','Test Father Three')
on conflict (id) do update set institute_id=excluded.institute_id,batch_id=excluded.batch_id,roll_no=excluded.roll_no,name=excluded.name,father_name=excluded.father_name;
insert into public.staff (id,institute_id,trainer_id,name,role,employment_type,designation,primary_trade_id,secondary_trade_ids,batch_ids,subject_id,multi_trade_allowed) values
('st-tst','inst-99999','TR-99001','Test Instructor','instructor','regular','Craft Instructor','tst','{}'::text[],array['tst-s1u1']::text[],null,false)
on conflict (id) do update set institute_id=excluded.institute_id,trainer_id=excluded.trainer_id,name=excluded.name,role=excluded.role,employment_type=excluded.employment_type,designation=excluded.designation,primary_trade_id=excluded.primary_trade_id,secondary_trade_ids=excluded.secondary_trade_ids,batch_ids=excluded.batch_ids,subject_id=excluded.subject_id,multi_trade_allowed=excluded.multi_trade_allowed;
